### ISSUE TITLE
Domoticz crashed, when I turn plugin on

### ISSUE THREAD

**Issue by JediMax27** [Whilser/Philips-Zhirui-LED-lamp#2]
Hallo!
Thank you for your work.
When I install plugin and add new device, domoticz not working properly. I's very slow and not show diveces, scenes etc. If I add turn off plugin , all works good.
Can you help me?

**Comment by Whilser** [comment]
Hello, turn on the debug option and show me log from Domoticz. Also check that option "Accept new Hardware Devices" in Settings - System is enabled.

**Comment by JediMax27** [comment]
Can you talk russian?

**Comment by JediMax27** [comment]
I reinstall miio and change php version.
Now working! But I have anoser problem - now I create anoser issue for it.
Thank you.
