### ISSUE TITLE
How to obtain token

### ISSUE THREAD

**Issue by blacksocket** [Whilser/Philips-Zhirui-LED-lamp#4]
Hi,

I am trying to get the token using many techniques without success from the Philips ZhiYi ceiling lamp (I have most updated firmware). I tried find the file on my smartphone from path: /data/data/com.xiaomi.smarthome/databases/miio2.db but it does not exist. Then I tried get it using miio --discover --sync described here https://github.com/aholstenson/miio/blob/master/docs/management.md also without success because im getting Token: ???. Could you please help how to get token from this lamp ?

Device ID: 86918471
Model info: Unknown
Address: 192.168.1.103
Token: ???
Support: Unknown

**Comment by Whilser** [comment]
Try the modified MiHome app for Android http://za.kapiba.ru/files/MiHome_5.5.53_vevs.apk. You will find the token in the information about the network.

**Comment by blacksocket** [comment]
Hi Whilser,

Many thanks for the tip! The link you provided no more exist however I have found the similar Mihome mod version on this wepage https://cloud.mail.ru/public/33J3/t817u4Snr using the newest one https://cloud.mail.ru/public/33J3/t817u4Snr/MiHome_5.5.6_vevs.apk and I  was able to get token. I installed the plugin and it works perfect! Thank you! ;-)
